config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :products, only: [:index]
  get "page/index"

  get "page/help"
  get "/login", to: "page#login"
  get "/detail", to: "page#detail"
  get "page/about"

  get "page/contact"
  get "cart/index"
  get "line_items/index"
  root "page#index"
  get "/order", to: "page#order"
 # get "/cart", to: "page#cart"
 get "page/cart"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :products
  belongs_to :user
  has_one :cart
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def login
  end

  def home
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @line_item = LineItem.new(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  @products = Product.all
  end

  def help
  end

  def about
  end

  def contact
  end

  def order

  end
  def cart
#@posts = Post.all
  end
  def login

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(user_name: params[:session][:user_name].downcase)
    if user && user.authenticate(params[:session][:user_pass])
    else
      flash[:danger] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

end

app/views/admin/_form.html.erb
<div class="body">
  <div id="wrapper">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="navbar-brand">
      <%= link_to "Hi Guy  , Have a nice day", index_path %>
      </div>
      <ul class="nav navbar-right top-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Smith <b class="caret"></b></a>
            <ul class="dropdown-menu">
            <li>
              <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
            </li>
            <li>
              <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
            </li>
            <li>
              <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
            </li>
            <li>
            <a href="#"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
            </li>
          </ul>
        </li>
      </ul>
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
          <li class="active">
            <%= link_to t(".home"), home_path %>
          </li>
          <li>
            <%= link_to t(".employees"), employees_path %>
          </li>
          <li>
            <%= link_to t(".order"), order_path %>
          </li>
          <li>
            <%= link_to t(".categoryproduct"), category_path %>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</div>

app/views/admin/category.html.erb
<% provide :title, t(".category")%>
<div class="body">
  <div id="wrapper">
    <%= render "admin/form"%>
    <div id="page-wrapper">
      <div class="container-fluid">
        <div class="row">
        <div class="col-lg-12">
          <h2 class="page-header"><%= t(".tablec")%></h2>
        </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
            <h2><%= t(".tablec")%></h2>
            <div class="table-responsive">
            <table class="table table-bordered table-hover">
              <thead>
                <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Pass</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                <td>1</td>
                <td>1265</td>
                <td>32.3%</td>
                </tr>
              </tbody>
            </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/employees.html.erb
<% provide :title, t(".employees") %>
<div class="body">
  <div id="wrapper">
    <%= render "admin/form"%>
    <div id="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <h2 class="page-header"><%= t(".tablee")%></h2>
          </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <h2><%= t(".tablee")%></h2>
                <div class="table-responsive">
                  <table class="table table-bordered table-hover">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Pass</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>1</td>
                        <td>1265</td>
                        <td>32.3%</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/admin/home.html.erb
<% provide :title, t(".home")%>
<div class="body">
  <div id="wrapper">
    <%= render "admin/form" %>
    <div id="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <h2 class="page-header"><%= t(".dashboard")%><small><%= t(".overview")%></small></h2>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-3">
                    <i class="fa fa-comments fa-5x"></i>
                  </div>
                <div class="col-xs-9 text-right">
                  <div class="huge">26</div>
                  <div><%= t(".comment")%></div>
                </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="panel panel-green">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-3">
                    <i class="fa fa-tasks fa-5x"></i>
                  </div>
                  <div class="col-xs-9 text-right">
                    <div class="huge">12</div>
                    <div><%= t(".task")%></div>
                  </div>
                </div>
              </div>
            </div>
         </div>
        <div class="col-lg-3 col-md-6">
          <div class="panel panel-yellow">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fa fa-shopping-cart fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                  <div class="huge">124</div>
                  <div><%= t(".neworder")%></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="panel panel-red">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fa fa-support fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                  <div class="huge">13</div>
                    <div><%= t(".support")%></div>
                </div>
              </div>
            </div>
            </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= image_tag("meodamdang.jpg", :alt => "meo dam dang") %>
    <%= render "admin/form" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/admin/order.html.erb
<% provide:title, t(".order")%>
<div class="body">
  <div id="wrapper">
    <%= render "admin/form"%>
    <div id="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <h2 class="page-header"><%= t(".tableo")%></h2>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
            <h2><%= t(".tableo")%></h2>
              <div class="table-responsive">
                <table class="table table-bordered table-hover">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Name</th>
                      <th>Pass</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>1</td>
                      <td>1265</td>
                      <td>32.3%</td>
                    </tr>
                  </tbody>
                </table>
               </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Your cart</h2>
<ul>
    <% @cart.line_items.each do |a| %>
    <li><%= a.product.title %></li>
    <% end %>
</ul>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/layouts/_body.html.erb
<div class="container">
  <ul class="nav nav-pills">
  <li role="presentation"><%= link_to t(".home"), root_path %></li>
  <li role="presentation"><%= link_to t(".maytinh"), "#" %></li>
  <li role="presentation"><%= link_to t(".dienthoai"), "#" %></li>
  <li role="presentation"><%= link_to t(".maytinhbang"), "#" %></li>
  <li role="presentation"><%= link_to t(".phukien"), "#" %></li>
  <li role="presentation"><%= link_to t(".tintuc"), "#" %></li>
</ul>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul><address>
      <li><strong><%=t ".hethong" %></strong></li>
      <li><%=t ".address1" %></li>
      <li><%=t ".address2" %></li>
      <li><%=t ".tel" %></li>
    </address>
    </ul>
  </nav>
    <nav>
    <ul>
      <li><strong><%=t ".about" %></strong></li>
      <li><%= link_to t(".quydinh"), "#" %></li>
      <li><%= link_to t(".chinhsach"), "#" %></li>
      <li><%= link_to t(".tuyendung"), "#" %></li>
    </ul>
  </nav>
    <nav>
    <ul>
      <li><strong><%=t ".dichvu" %></strong></li>
      <li><%= link_to t(".tragop"),"#" %></li>
      <li><%= link_to t(".doitra"), "#" %></li>
      <li><%= link_to t(".vanchuyen"), "#" %></li>
      <li><%= link_to t(".baohanh"), "#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
      <%= link_to t(".logo"), root_path, id: "logo" %>
    <div class="navbar-header">
    <form class="navbar-form navbar-left">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Tìm kiếm sản phẩm">
      </div>
        <button type="submit" class="btn btn-default">
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          <%=t ".search" %>
        </button>
    </form>
    </div>
  </div>
</header>

app/views/layouts/_left.html.erb
<head>
<div class="mainbody left-fl">
  <div class="mainbody-content w1020px marginauto">
      <div class="left-area w220px left-fl">

          <div class="block menu-list branch-mobile "><h4 class="pd5x10"> Danh mục</h4>
              <ul class="nav nav-list w190px bs-docs-sidenav ">
                  <li>
                        <a href="#" >
                        <span class="branch-mobile">Apple</span>
                          <span class="branch-mobile-logo"></span>
                        </a>
                        <ul >
                          <li><a href="#">Iphone</a></li>
                            <li><a href="#">Ipad</a></li>
                            <li><%= link_to t(".suachua"), "#" %></li>
                            <li><%= link_to t(".phukien"), "#" %></li>
                        </ul>
                    </li>
                    <li><a href="#">
                        <span class="branch-mobile">Nokia</span>
                            <span class="branch-mobile-logo"></span>
                        </a>
                        <ul >
                          <li><a href="#">Lumia</a></li>
                            <li><%= link_to t(".dientnew"), "#" %></li>
                            <li><%= link_to t(".dientold"), "#" %></li>
                            <li><%= link_to t(".suachua"), "#" %></li>
                            <li><%= link_to t(".phukien"), "#" %></li>
                        </ul>
                    </li>
                    <li ><a href="#" >
                        <span class="branch-mobile">SamSung</span>
                            <span class="branch-mobile-logo"></span>
                        </a>
                        <ul >
                          <li><a href="#">Galaxy </a></li>
                            <li><%= link_to t(".dientnew"), "#" %></li>
                            <li><%= link_to t(".dientold"), "#" %></li>
                            <li><%= link_to t(".suachua"), "#" %></li>
                            <li><%= link_to t(".phukien"), "#" %></li>
                        </ul>
                    </li>
                    <li><a href="#" >
                        <span class="branch-mobile">LG Electronic</span>
                            <span class="branch-mobile-logo"></span>
                        </a>
                        <ul >
                          <li><a href="#">Optimus </a></li>
                            <li><%= link_to t(".dientnew"), "#" %></li>
                            <li><%= link_to t(".dientold"), "#" %></li>
                            <li><%= link_to t(".suachua"), "#" %></li>
                            <li><%= link_to t(".phukien"), "#" %></li>
                        </ul>
                    </li>
                    <li><a href="#" >
                        <span class="branch-mobile">Sony</span>
                            <span class="branch-mobile-logo"></span>
                        </a>
                        <ul >
                          <li><a href="#">Xperia </a></li>
                            <li><%= link_to t(".dientnew"), "#" %></li>
                            <li><%= link_to t(".dientold"), "#" %></li>
                            <li><%= link_to t(".suachua"), "#" %></li>
                            <li><%= link_to t(".phukien"), "#" %></li>
                        </ul>
                    </li>
                    <li><a href="#" >
                        <span class="branch-mobile">HTC</span>
                            <span class="branch-mobile-logo"></span>
                        </a>
                        <ul >
                            <li><%= link_to t(".dientnew"), "#" %></li>
                            <li><%= link_to t(".dientold"), "#" %></li>
                            <li><%= link_to t(".suachua"), "#" %></li>
                            <li><%= link_to t(".phukien"), "#" %></li>
                        </ul>
                    </li>
                    <li><a href="#" >
                        <span class="branch-mobile">Sky Pantech</span>
                            <span class="branch-mobile-logo"></span>
                        </a>
                        <ul >
                            <li><%= link_to t(".dientnew"), "#" %></li>
                            <li><%= link_to t(".dientold"), "#" %></li>
                            <li><%= link_to t(".suachua"), "#" %></li>
                            <li><%= link_to t(".phukien"), "#" %></li>
                        </ul>
                    </li>
                    <li><a href="#" >
                        <span class="branch-mobile">Oppo</span>
                            <span class="branch-mobile-logo"></span>
                        </a>
                        <ul >
                            <li><%= link_to t(".dientnew"), "#" %></li>
                            <li><%= link_to t(".dientold"), "#" %></li>
                            <li><%= link_to t(".suachua"), "#" %></li>
                            <li><%= link_to t(".phukien"), "#" %></li>
                        </ul>
                    </li>

                </ul>
            </div>

            <div class="block menu-list accessories"><h4 class="pd5x10">Phụ kiện</h4>
              <ul class="nav nav-list w190px bs-docs-sidenav">
                  <li><a href="#" >Tai nghe</a></li>
                    <li><a href="#" >Tai nghe Blutooth</a></li>
                    <li><a href="#">Pin</a></li>
                    <li><a href="#" >Vỏ máy</a></li>
                    <li><a href="#" >Ốp lưng</a></li>
                </ul>
            </div>

            <div class="block menu-list supportlive"><h4 class="pd5x10 ">Hỗ trợ trực tuyến</h4>
              <ul class="nav nav-list w190px ">
                  <li><a href="#">
                    Kinh doanh 1:
                    </a></li>
                    <ul>0978.102.493</ul>
                    <li><a href="#">
                    Kinh doanh 2:
                    </a></li>
                    <ul>0123.102.245</ul>
                </ul>
            </div>

        </div>
        <div class="right-area w775px left-fl pd10">

  <!-- Start WOWSlider.com HEAD section -->
  <link rel="stylesheet" type="text/css" href="css/wowhome.css" />
  <script type="text/javascript" src="js/wowslider/jquery.js"></script>
  <!-- End WOWSlider.com HEAD section -->
</head>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minh Tien Mobile</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
  <%= render "layouts/header" %>
  <%= render "layouts/body" %>
    <div class="container">
      <%= render "layouts/left" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/page/_product.html.erb
<li>
  <%= product.name %>
</li>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/detail.html.erb
<div><h1>THÔNG TIN CHI TIẾT</h1>
<ul><li>3G:HSPA 42.2/5.76 Mbps, EV-DO Rev.A 3.1 Mbps</li>
<li>4G:LTE-A (3CA) Cat12 600/150 Mbps</li>
<li>SIM:Nano-SIM</li>
<li>Kích thước:143.6 x 70.9 x 7.7 mm (5.65 x 2.79 x 0.30 in)</li>
<li>Trọng lượng:174 g (6.14 oz)</li>
<li>Màn hình:Cảm ứng điện dung OLED, 16 triệu màu</li>
<li>Kích thước màn hình:1125 x 2436 pixels, 5.8 inches (~458 ppi mật độ điểm ảnh)</li>
<li>Bộ nhớ trong:256 GB, 3 GB RAM</li>
<li>Khe cắm thẻ nhớ:Không</li>
<li>WLAN:Wi-Fi 802.11 a/b/g/n/ac, dual-band, hotspot</li>
<li>Bluetooth:5.0, A2DP, LE</li>
<li>USB:2.0</li>
<li>NFC:Chỉ sử dụng Apple Pay</li>
<li>GPS:A-GPS, GLONASS, GALILEO, QZSS</li>
<li>Hệ điều hành:iOS 11.1</li>
<li>Chipset:Apple A11 Bionic APL1W72</li>
<li>CPU:2x 2.1 GHz Monsoon , 4x 2.1 GHz Mistral</li>
<li>GPU:Apple GPU (3 lõi đồ họa)</li>
<li>Bộ cảm biến:Nhận diện khuôn mặt, gia tốc, la bàn, khoảng cách, con quay quy hồi, phong vũ biểu</li>
<li>Camera chính:2x 12 MP, f/1.8, f/2.4, tự động lấy nét nhận diện theo giai đoạn, 2x zoom quang học, OIS, 4 LED flash (2 tone)</li>
<li>Camera phụ:7 MP, f/2.2, 1080p@30fps, 720p@240fps, nhận diện khuôn mặt, HDR, panorama</li>
<li>Video:2160p@24/30/60fps, 1080p@30/60/120/240fps</li>
<li>Pin:Li-Ion 2716 mAh</li>
<li>Thời gian đàm thoại:21 giờ (3G)</li>
<li>Thời gian chờ:384 giờ (3G)</li>
<li>Thời gian chơi nhạc:60 giờ (không dây)</li>
</ul>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= link_to("Đặt hàng ngay", order_path, class: "btn btn-info") %>
      <%= link_to("Tiếp tục mua hàng",root_path, class: "btn btn-default") %>
    </div>
</div>

app/views/page/help.html.erb
<h1>Page#help</h1>
<p>Find me in app/views/page/help.html.erb</p>